/*
 *****************************************************************************
 *                                                                           *
 *                 IMPINJ CONFIDENTIAL AND PROPRIETARY                       *
 *                                                                           *
 * This source code is the sole property of Impinj, Inc.  Reproduction or    *
 * utilization of this source code in whole or in part is forbidden without  *
 * the prior written consent of Impinj, Inc.                                 *
 *                                                                           *
 * (c) Copyright Impinj, Inc. 2010. All rights reserved.                     *
 *                                                                           *
 *****************************************************************************
 */

/*
 *****************************************************************************
 *
 * $Id: macerror.h 80168 2012-04-17 22:42:13Z rsales $
 * 
 * Description:
 *
 *   This file is automatically generated.
 *   Automatic Generator File: source_macerror.pl (Version 63541)
 *   Reference File: mac_errors.xml (Version 80161)
 *
 *****************************************************************************
 */

#ifndef H_MACERROR_H
#define H_MACERROR_H

/* MAC Error Codes
   These error codes are exposed via the MAC_ERROR register.
   Values are returned as the error code value in a command response. */

/* Error Modules */

// 0x00 - Core State Machine 
// 0x01 - Host Interface 
// 0x02 - RFID Protocol 
// 0x03 - RFID Transciever Control 
// 0x04 - GPIO, MCU support, OEM Config 
// 0x06 - RFID Transceiver Low Level Interface 
// 0x07 - BIST 




/* Module: (0x00) Core State Machine */

#define MACERR_SUCCESS                           0x0000
#define CSM_ERR_UNKNOWNCMD                       0x0001
#define CSM_ERR_PREEXECPROC                      0x0002
#define CSM_ERR_POSTEXECPROC                     0x0003
#define CSM_ERR_BADENGTESTSUBCMD                 0x0004
#define CSM_ERR_MBPRDADDR                        0x0005
#define CSM_ERR_MBPWRADDR                        0x0006
#define CSM_ERR_SUBSYSINIT_CPU                   0x0007
#define CSM_ERR_SUBSYSINIT_DBG                   0x0008
#define CSM_ERR_SUBSYSINIT_CSM                   0x0009
#define CSM_ERR_SUBSYSINIT_OEMCFG                0x000A
#define CSM_ERR_SUBSYSINIT_HOSTIF                0x000B
#define CSM_ERR_SUBSYSINIT_TILIF                 0x000C
#define CSM_ERR_SUBSYSINIT_BIST                  0x000D
#define CSM_ERR_SUBSYSINIT_GPIO                  0x000F
#define CSM_ERR_SUBSYSINIT_RFTC                  0x0010
#define CSM_ERR_SUBSYSINIT_PROT                  0x0011
#define CSM_ERR_PROTSCHED_UNKST                  0x0012
#define CSM_ERR_PROTSCHED_AMBANT                 0x0013
#define CSM_ERR_PROTSCHED_NODESC                 0x0014
#define CSM_ERR_PROTSCHED_PORTDEF                0x0015
#define CSM_ERR_PROTSCHED_NOFRQCH                0x0016
#define CSM_ERR_PROTSCHED_BADREGION              0x0017
#define CSM_ERR_PROTSCHED_BADFTIME               0x0018
#define CSM_ERR_PROTSCHED_FTUNETO                0x0019
#define CSM_ERR_SUBSYSINIT_OEMHWOPTS             0x001A
#define CSM_ERR_SUBSYSINIT_NVMEMUPD              0x001B
#define CSM_ERR_BAD_RESET_KEY                    0x001C
#define CSM_ERR_DEV_RESET_FAILED                 0x001D
#define CSM_ERR_NVMEMUPD_ABORT_MACERRNO          0x001E
#define CSM_ERR_NVMEMUPD_INT_MEMBNDS             0x001F
#define CSM_ERR_NVMEMUPD_ENTRYKEY                0x0020
#define CSM_ERR_NVMEMUPD_NVFLUSH                 0x0021
#define CSM_ERR_NVMEMUPD_WRVERFAIL               0x0022
#define CSM_ERR_INVAL_START_CHAN                 0x0023
#define CSM_ERR_PROTSCHED_UNK_ALGO               0x0024
#define CSM_ERR_INVAL_PWRMODE                    0x0025
#define CSM_ERR_PWRMODE_CORRUPT                  0x0026
#define CSM_ERR_NVMEMUPD_TXFAIL                  0x0027
#define CSM_ERR_NVMEMUPD_UPD_BOUNDS              0x0028
#define CSM_ERR_NVMEMUPD_UNKNOWN                 0x0029
#define CSM_ERR_NVMEMUPD_RXTO                    0x002A
#define CSM_ERR_GPIO_NOTAVAIL                    0x002B
#define CSM_ERR_ANT_NOTAVAIL                     0x002C
#define CSM_ERR_CMDNOTAVAILABLE                  0x002D
#define CSM_ERR_NOCORDICDEF                      0x002E
#define CSM_ERR_SUBSYSINIT_DEBUG                 0x002F
#define CSM_ERR_SUBSYSINIT_TRACE                 0x0030
#define CSM_ERR_BUILD_TARGET_DEVICE_MISMATCH     0x0031
#define CSM_ERR_DIAGNOSTICS                      0x0032
#define CSM_ERR_SUBSYSINIT_HOSTIFREGS_INIT       0x0033
#define CSM_ERR_SUBSYSINIT_HANDSHAKE             0x0034
#define CSM_ERR_NVMEMUPD_INVALID_MODE            0x0035
#define CSM_ERR_INVALID_CMD_WHILE_IN_CRIT_ERROR  0x0036
#define CSM_ERR_CRITICAL_ERROR_UNKNOWN           0x0037


/* Module: (0x01) Host Interface */

#define RESERVED_0x0101                          0x0101
#define HOSTIF_ERR_USBDESC                       0x0102
#define HOSTIF_ERR_USBDESCIDX                    0x0103
#define HOSTIF_ERR_USBTXEP0                      0x0104
#define RESERVED_0x0105                          0x0105
#define HOSTIF_ERR_USBRXBUFFSZ                   0x0106
#define HOSTIF_ERR_RXUNKNOWN                     0x0107
#define HOSTIF_ERR_TXUNKNOWN                     0x0108
#define HOSTIF_ERR_BADIFSTATE                    0x0109
#define RESERVED_0x010A                          0x010A
#define HOSTIF_ERR_REGADDR                       0x010B
#define RESERVED_0x010C                          0x010C
#define HOSTIF_ERR_USBDESCINIT                   0x010D
#define HOSTIF_ERR_SELECTORBNDS                  0x010E
#define RESERVED_0x010F                          0x010F
#define HOSTIF_ERR_PKTALIGN                      0x0110
#define HOSTIF_ERR_BADRAWMODE                    0x0111
#define HOSTIF_ERR_UNKLNKSTATE                   0x0112
#define HOSTIF_ERR_UNKUSBSETUP                   0x0113
#define HOSTIF_ERR_UARTRXBUFFSZ                  0x0114
#define HOSTIF_ERR_RAWMODECTL                    0x0115
#define HOSTIF_ERR_UNKHOSTIF                     0x0116
#define HOSTIF_ERR_UNKREGSTD                     0x0117
#define HOSTIF_ERR_DEBUGID                       0x0118
#define HOSTIF_ERR_DEBUGOVERFLOW                 0x0119
#define HOSTIF_ERR_REGREADONLY                   0x011A
#define HOSTIF_ERR_REGWRITEONLY                  0x011B
#define HOSTIF_ERR_BADREGIONINITVALUES           0x011C
#define HOSTIF_ERR_INVALIDENGTESTARG             0x011D
#define HOSTIF_ERR_INVALIDSETFREQARG             0x011E
#define HOSTIF_ERR_INVALID_RSSI_FILTERING        0x011F
#define HOSTIF_ERR_INVALID_TAGACC_CNT            0x0120
#define HOSTIF_ERR_INVALID_BW_MODE               0x0121
#define HOSTIF_ERR_OEM_MAC_REG_INIT_CTRL_ERROR   0x0122
#define HOSTIF_ERR_OEM_MAC_REG_INIT_WRITE_ERROR  0x0123


/* Module: (0x02) RFID Protocol */

#define PROTOCOL_ERR_TRUNCATION_UNSUPPORTED      0x0200


/* Module: (0x03) RFID Transciever Control */

#define RFTC_ERR_BADFRQCHAN                      0x0300
#define RFTC_ERR_BADHOPMODE                      0x0301
#define RFTC_ERR_PLLFAILEDTOLOCK                 0x0302
#define RFTC_ERR_XCVRADC_TIMEDOUT                0x0303
#define RFTC_ERR_FILTTUNE_TIMEOUT                0x0304
#define RFTC_ERR_AMBIENTTEMPTOOHOT               0x0305
#define RFTC_ERR_XCVRTEMPTOOHOT                  0x0306
#define RFTC_ERR_PATEMPTOOHOT                    0x0307
#define RFTC_ERR_PADELTATEMPTOOBIG               0x0308
#define RFTC_ERR_REVPWRLEVTOOHIGH                0x0309
#define RFTC_ERR_BADIFLNAGAIN                    0x030A
#define RFTC_ERR_TXRF_BIT_FAILED                 0x030B
#define RFTC_ERR_TXRF_BYTE_FAILED                0x030C
#define RFTC_ERR_TXRF_EOT_FAILED                 0x030D
#define RFTC_ERR_TXRF_PREAM_FAILED               0x030E
#define RFTC_ERR_TXRF_FSYNC_FAILED               0x030F
#define RFTC_ERR_RXRF_ISR_TIMEOUT                0x0310
#define RFTC_ERR_INVALIDLINKPARMS                0x0311
#define RFTC_ERR_RXRF_INTERPKTTIMEOUT            0x0312
#define RFTC_ERR_NO_LINKPROFHDR                  0x0313
#define RFTC_ERR_PROFILE_INVALID                 0x0314
#define RFTC_ERR_DBMVALOUTOFRANGE                0x0315
#define RFTC_ERR_FWDPWRLEVTOOHIGH                0x0316
#define RFTC_ERR_NO_GROSSPWRENTRY                0x0317
#define RFTC_ERR_TARGETPWRTOOHIGH                0x0318
#define RESERVED_0x0318                          0x0319
#define RFTC_ERR_ANTENNADISCONNECTED             0x031A
#define RFTC_ERR_UNREC_HWOPTFORMAT               0x031B
#define RFTC_ERR_HWOPT_BADFWDPWROPT              0x031C
#define RFTC_ERR_HWOPT_BADREVPWROPT              0x031D
#define RFTC_ERR_HWOPT_BADDRMFILTOPT             0x031E
#define RFTC_ERR_HWOPT_BADAMBTEMPOPT             0x031F
#define RFTC_ERR_HWOPT_BADPATEMPOPT              0x0320
#define RFTC_ERR_HWOPT_BADXCVRTEMPOPT            0x0321
#define RFTC_ERR_HWOPT_BADANTSENSOPT             0x0322
#define RFTC_ERR_BADIFLNAAGCRANGE                0x0323
#define RFTC_ERR_LPROFBADSELECTOR                0x0324
#define RFTC_ERR_BADXCVRADDR                     0x0325
#define RFTC_ERR_XCVRADDRNOTINLIST               0x0326
#define RFTC_ERR_BAD_RFLNA_GAIN_REQ              0x0327
#define RFTC_ERR_BAD_IFLNA_GAIN_REQ              0x0328
#define RFTC_ERR_BAD_AGCMIX_GAIN_REQ             0x0329
#define RFTC_ERR_HWOPT_BADFWDPWRCOMPOPT          0x032A
#define RFTC_ERR_INVALID_PLL_DIVIDER_VALUE       0x032B
#define RFTC_ERR_SJC_EXTERNALLOTOOLOW            0x032C
#define RFTC_ERR_SJC_EXTERNALLONOTSELECTED       0x032D
#define RFTC_ERR_BADLOSOURCE                     0x032E
#define RFTC_ERR_GENERALRANDOMDATA               0x032F
#define RFTC_ERR_XVCR_HEALTH_CHECK_FAIL          0x0330
#define RFTC_ERR_INVALID_OEM_PROFILE_HEADER      0x0331
#define RFTC_ERR_AUTO_READ_RX_FIFO               0x0332
#define RFTC_ERR_DC_OFFSET_CALIBRATION           0x0333
#define RFTC_ERR_LBT_RSSI_CALIBRATION            0x0334
#define RFTC_ERR_PA_BIAS_CAL_CONFIG              0x0335
#define RFTC_ERR_FWDPWRLEVERROR                  0x0336
#define RFTC_ERR_HWOPT_BADPABIASDACCTL           0x0337
#define RFTC_ERR_PA_BIAS_CAL_MEASUREMENT         0x0338
#define RFTC_ERR_PA_BIAS_CAL_NOT_FOUND           0x0339
#define RFTC_ERR_GROSSGAIN_CONFIG_INVALID        0x033A
#define RFTC_ERR_SJC_NOT_AVAILABLE_R500          0x033B
#define RFTC_ERR_GROSSGAIN_CALIBRATION           0x033C


/* Module: (0x04) GPIO, MCU support, OEM Config */

#define IO_INVAL_RDMASK                          0x0401
#define IO_INVAL_WRMASK                          0x0402
#define IO_INVAL_PTR_RAM                         0x0403
#define IO_INVAL_PTR_NV                          0x0404
#define IO_INVAL_PTR_NV_ALIGN                    0x0405
#define IO_NV_LOCK_ERR                           0x0406
#define IO_NV_PROG_ERR                           0x0407
#define IO_OEMCFG_ADDR_BOUNDS                    0x0408
#define IO_OEMCFG_NV_BOUNDS                      0x0409
#define IO_OEMCFG_FMT_KEY                        0x040A
#define IO_OEMCFG_FLUSH                          0x040B
#define IO_OEMCFG_FORMAT                         0x040C
#define IO_INVAL_IORSVD                          0x040D
#define IO_OEMCFG_STRING_TYPE                    0x040E
#define IO_OEMCFG_STRING_LENGTH                  0x040F
#define IO_OEMCFG_STRING_CHARACTER               0x0410
#define IO_OEMCFG_STRING_CURRENT_INVALID         0x0411
#define IO_OEMCFG_FORMAT_KEY_INVALID             0x0412
#define IO_OEMCFG_FORMAT_CONFIGURATION_INVALID   0x0413
#define IO_INVAL_NV_SECTOR                       0x0414


/* Module: (0x06) RFID Transceiver Low Level Interface */

#define TILDENIF_ERR_ADDRMISMAT                  0x0601
#define TILDENIF_ERR_RDFAILSAFE                  0x0602
#define TILDENIF_ERR_INVALPWRST                  0x0603
#define TILDENIF_ERR_INVALID_SETTING_R500        0x0604


/* Module: (0x07) BIST */

#define BIST_ERR_RF_IO_REG_CHK                   0x0701
#define BIST_ERR_RF_REG_BITS                     0x0702

#endif //H_MACERROR_H

/* End of generated file */

